Update clientkit
firstandthird/mediamanager pull request #48
Opened 2018-11-26 15:49 UTC by AlejandroPerezMartin

2018-11-26 18:24 UTC, jgallen23 commented on docker-compose.yml
> +    VIRTUAL_PORT: 8080
don't need this

2018-12-18 00:10 UTC, dawnerd requested changes

2018-12-18 00:10 UTC, dawnerd commented on Dockerfile
> +FROM firstandthird/node:10.10
```suggestion
FROM firstandthird/node:10.10-2-onbuild
```

2018-12-18 00:10 UTC, dawnerd commented on DockerfileDev
> +FROM firstandthird/node:10.10
```suggestion
FROM firstandthird/node:10.10-2-dev
```

2019-01-03 07:48 UTC, dawnerd approved these changes

2019-01-04 22:53 UTC, merged